// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package fr.maelgui.wordclockmanager;

public final class MessagesProto {
    private MessagesProto() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface MessageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Message)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional uint64 value = 1;</code>
         * @return Whether the value field is set.
         */
        boolean hasValue();
        /**
         * <code>optional uint64 value = 1;</code>
         * @return The value.
         */
        long getValue();

        /**
         * <code>required .Message.Key key = 2;</code>
         * @return Whether the key field is set.
         */
        boolean hasKey();
        /**
         * <code>required .Message.Key key = 2;</code>
         * @return The key.
         */
        fr.maelgui.wordclockmanager.MessagesProto.Message.Key getKey();
    }
    /**
     * Protobuf type {@code Message}
     */
    public static final class Message extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Message)
            MessageOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use Message.newBuilder() to construct.
        private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private Message() {
            key_ = 0;
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new Message();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private Message(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {
                            bitField0_ |= 0x00000001;
                            value_ = input.readUInt64();
                            break;
                        }
                        case 16: {
                            int rawValue = input.readEnum();
                            @SuppressWarnings("deprecation")
                            fr.maelgui.wordclockmanager.MessagesProto.Message.Key value = fr.maelgui.wordclockmanager.MessagesProto.Message.Key.valueOf(rawValue);
                            if (value == null) {
                                unknownFields.mergeVarintField(2, rawValue);
                            } else {
                                bitField0_ |= 0x00000002;
                                key_ = rawValue;
                            }
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return fr.maelgui.wordclockmanager.MessagesProto.internal_static_Message_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return fr.maelgui.wordclockmanager.MessagesProto.internal_static_Message_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            fr.maelgui.wordclockmanager.MessagesProto.Message.class, fr.maelgui.wordclockmanager.MessagesProto.Message.Builder.class);
        }

        /**
         * Protobuf enum {@code Message.Key}
         */
        public enum Key
                implements com.google.protobuf.ProtocolMessageEnum {
            /**
             * <pre>
             * RTC
             * </pre>
             *
             * <code>TIME = 0;</code>
             */
            TIME(0),
            /**
             * <code>TEMPERATURE = 1;</code>
             */
            TEMPERATURE(1),
            /**
             * <code>TEMPERATURES = 2;</code>
             */
            TEMPERATURES(2),
            /**
             * <pre>
             * Function related
             * </pre>
             *
             * <code>TIMER = 3;</code>
             */
            TIMER(3),
            /**
             * <pre>
             * Settings
             * </pre>
             *
             * <code>MODE = 4;</code>
             */
            MODE(4),
            /**
             * <code>FUNCTION = 5;</code>
             */
            FUNCTION(5),
            /**
             * <code>BRIGHTNESS = 6;</code>
             */
            BRIGHTNESS(6),
            /**
             * <code>THRESHOLD = 7;</code>
             */
            THRESHOLD(7),
            /**
             * <code>ROTATION = 8;</code>
             */
            ROTATION(8),
            /**
             * <pre>
             * Response
             * </pre>
             *
             * <code>OK = 9;</code>
             */
            OK(9),
            /**
             * <code>ERROR = 10;</code>
             */
            ERROR(10),
            ;

            /**
             * <pre>
             * RTC
             * </pre>
             *
             * <code>TIME = 0;</code>
             */
            public static final int TIME_VALUE = 0;
            /**
             * <code>TEMPERATURE = 1;</code>
             */
            public static final int TEMPERATURE_VALUE = 1;
            /**
             * <code>TEMPERATURES = 2;</code>
             */
            public static final int TEMPERATURES_VALUE = 2;
            /**
             * <pre>
             * Function related
             * </pre>
             *
             * <code>TIMER = 3;</code>
             */
            public static final int TIMER_VALUE = 3;
            /**
             * <pre>
             * Settings
             * </pre>
             *
             * <code>MODE = 4;</code>
             */
            public static final int MODE_VALUE = 4;
            /**
             * <code>FUNCTION = 5;</code>
             */
            public static final int FUNCTION_VALUE = 5;
            /**
             * <code>BRIGHTNESS = 6;</code>
             */
            public static final int BRIGHTNESS_VALUE = 6;
            /**
             * <code>THRESHOLD = 7;</code>
             */
            public static final int THRESHOLD_VALUE = 7;
            /**
             * <code>ROTATION = 8;</code>
             */
            public static final int ROTATION_VALUE = 8;
            /**
             * <pre>
             * Response
             * </pre>
             *
             * <code>OK = 9;</code>
             */
            public static final int OK_VALUE = 9;
            /**
             * <code>ERROR = 10;</code>
             */
            public static final int ERROR_VALUE = 10;


            public final int getNumber() {
                return value;
            }

            /**
             * @param value The numeric wire value of the corresponding enum entry.
             * @return The enum associated with the given numeric wire value.
             * @deprecated Use {@link #forNumber(int)} instead.
             */
            @java.lang.Deprecated
            public static Key valueOf(int value) {
                return forNumber(value);
            }

            /**
             * @param value The numeric wire value of the corresponding enum entry.
             * @return The enum associated with the given numeric wire value.
             */
            public static Key forNumber(int value) {
                switch (value) {
                    case 0: return TIME;
                    case 1: return TEMPERATURE;
                    case 2: return TEMPERATURES;
                    case 3: return TIMER;
                    case 4: return MODE;
                    case 5: return FUNCTION;
                    case 6: return BRIGHTNESS;
                    case 7: return THRESHOLD;
                    case 8: return ROTATION;
                    case 9: return OK;
                    case 10: return ERROR;
                    default: return null;
                }
            }

            public static com.google.protobuf.Internal.EnumLiteMap<Key>
            internalGetValueMap() {
                return internalValueMap;
            }
            private static final com.google.protobuf.Internal.EnumLiteMap<
                    Key> internalValueMap =
                    new com.google.protobuf.Internal.EnumLiteMap<Key>() {
                        public Key findValueByNumber(int number) {
                            return Key.forNumber(number);
                        }
                    };

            public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
                return getDescriptor().getValues().get(ordinal());
            }
            public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
                return getDescriptor();
            }
            public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
                return fr.maelgui.wordclockmanager.MessagesProto.Message.getDescriptor().getEnumTypes().get(0);
            }

            private static final Key[] VALUES = values();

            public static Key valueOf(
                    com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
                if (desc.getType() != getDescriptor()) {
                    throw new java.lang.IllegalArgumentException(
                            "EnumValueDescriptor is not for this type.");
                }
                return VALUES[desc.getIndex()];
            }

            private final int value;

            private Key(int value) {
                this.value = value;
            }

            // @@protoc_insertion_point(enum_scope:Message.Key)
        }

        private int bitField0_;
        public static final int VALUE_FIELD_NUMBER = 1;
        private long value_;
        /**
         * <code>optional uint64 value = 1;</code>
         * @return Whether the value field is set.
         */
        @java.lang.Override
        public boolean hasValue() {
            return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>optional uint64 value = 1;</code>
         * @return The value.
         */
        @java.lang.Override
        public long getValue() {
            return value_;
        }

        public static final int KEY_FIELD_NUMBER = 2;
        private int key_;
        /**
         * <code>required .Message.Key key = 2;</code>
         * @return Whether the key field is set.
         */
        @java.lang.Override public boolean hasKey() {
            return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>required .Message.Key key = 2;</code>
         * @return The key.
         */
        @java.lang.Override public fr.maelgui.wordclockmanager.MessagesProto.Message.Key getKey() {
            @SuppressWarnings("deprecation")
            fr.maelgui.wordclockmanager.MessagesProto.Message.Key result = fr.maelgui.wordclockmanager.MessagesProto.Message.Key.valueOf(key_);
            return result == null ? fr.maelgui.wordclockmanager.MessagesProto.Message.Key.TIME : result;
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasKey()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) != 0)) {
                output.writeUInt64(1, value_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                output.writeEnum(2, key_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(1, value_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(2, key_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof fr.maelgui.wordclockmanager.MessagesProto.Message)) {
                return super.equals(obj);
            }
            fr.maelgui.wordclockmanager.MessagesProto.Message other = (fr.maelgui.wordclockmanager.MessagesProto.Message) obj;

            if (hasValue() != other.hasValue()) return false;
            if (hasValue()) {
                if (getValue()
                        != other.getValue()) return false;
            }
            if (hasKey() != other.hasKey()) return false;
            if (hasKey()) {
                if (key_ != other.key_) return false;
            }
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasValue()) {
                hash = (37 * hash) + VALUE_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                        getValue());
            }
            if (hasKey()) {
                hash = (37 * hash) + KEY_FIELD_NUMBER;
                hash = (53 * hash) + key_;
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static fr.maelgui.wordclockmanager.MessagesProto.Message parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static fr.maelgui.wordclockmanager.MessagesProto.Message parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static fr.maelgui.wordclockmanager.MessagesProto.Message parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static fr.maelgui.wordclockmanager.MessagesProto.Message parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static fr.maelgui.wordclockmanager.MessagesProto.Message parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static fr.maelgui.wordclockmanager.MessagesProto.Message parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static fr.maelgui.wordclockmanager.MessagesProto.Message parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static fr.maelgui.wordclockmanager.MessagesProto.Message parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static fr.maelgui.wordclockmanager.MessagesProto.Message parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static fr.maelgui.wordclockmanager.MessagesProto.Message parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static fr.maelgui.wordclockmanager.MessagesProto.Message parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static fr.maelgui.wordclockmanager.MessagesProto.Message parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(fr.maelgui.wordclockmanager.MessagesProto.Message prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code Message}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Message)
                fr.maelgui.wordclockmanager.MessagesProto.MessageOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return fr.maelgui.wordclockmanager.MessagesProto.internal_static_Message_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return fr.maelgui.wordclockmanager.MessagesProto.internal_static_Message_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                fr.maelgui.wordclockmanager.MessagesProto.Message.class, fr.maelgui.wordclockmanager.MessagesProto.Message.Builder.class);
            }

            // Construct using fr.maelgui.wordclockmanager.MessagesProto.Message.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                value_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000001);
                key_ = 0;
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return fr.maelgui.wordclockmanager.MessagesProto.internal_static_Message_descriptor;
            }

            @java.lang.Override
            public fr.maelgui.wordclockmanager.MessagesProto.Message getDefaultInstanceForType() {
                return fr.maelgui.wordclockmanager.MessagesProto.Message.getDefaultInstance();
            }

            @java.lang.Override
            public fr.maelgui.wordclockmanager.MessagesProto.Message build() {
                fr.maelgui.wordclockmanager.MessagesProto.Message result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public fr.maelgui.wordclockmanager.MessagesProto.Message buildPartial() {
                fr.maelgui.wordclockmanager.MessagesProto.Message result = new fr.maelgui.wordclockmanager.MessagesProto.Message(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.value_ = value_;
                    to_bitField0_ |= 0x00000001;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.key_ = key_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof fr.maelgui.wordclockmanager.MessagesProto.Message) {
                    return mergeFrom((fr.maelgui.wordclockmanager.MessagesProto.Message)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(fr.maelgui.wordclockmanager.MessagesProto.Message other) {
                if (other == fr.maelgui.wordclockmanager.MessagesProto.Message.getDefaultInstance()) return this;
                if (other.hasValue()) {
                    setValue(other.getValue());
                }
                if (other.hasKey()) {
                    setKey(other.getKey());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                if (!hasKey()) {
                    return false;
                }
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                fr.maelgui.wordclockmanager.MessagesProto.Message parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (fr.maelgui.wordclockmanager.MessagesProto.Message) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private long value_ ;
            /**
             * <code>optional uint64 value = 1;</code>
             * @return Whether the value field is set.
             */
            @java.lang.Override
            public boolean hasValue() {
                return ((bitField0_ & 0x00000001) != 0);
            }
            /**
             * <code>optional uint64 value = 1;</code>
             * @return The value.
             */
            @java.lang.Override
            public long getValue() {
                return value_;
            }
            /**
             * <code>optional uint64 value = 1;</code>
             * @param value The value to set.
             * @return This builder for chaining.
             */
            public Builder setValue(long value) {
                bitField0_ |= 0x00000001;
                value_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional uint64 value = 1;</code>
             * @return This builder for chaining.
             */
            public Builder clearValue() {
                bitField0_ = (bitField0_ & ~0x00000001);
                value_ = 0L;
                onChanged();
                return this;
            }

            private int key_ = 0;
            /**
             * <code>required .Message.Key key = 2;</code>
             * @return Whether the key field is set.
             */
            @java.lang.Override public boolean hasKey() {
                return ((bitField0_ & 0x00000002) != 0);
            }
            /**
             * <code>required .Message.Key key = 2;</code>
             * @return The key.
             */
            @java.lang.Override
            public fr.maelgui.wordclockmanager.MessagesProto.Message.Key getKey() {
                @SuppressWarnings("deprecation")
                fr.maelgui.wordclockmanager.MessagesProto.Message.Key result = fr.maelgui.wordclockmanager.MessagesProto.Message.Key.valueOf(key_);
                return result == null ? fr.maelgui.wordclockmanager.MessagesProto.Message.Key.TIME : result;
            }
            /**
             * <code>required .Message.Key key = 2;</code>
             * @param value The key to set.
             * @return This builder for chaining.
             */
            public Builder setKey(fr.maelgui.wordclockmanager.MessagesProto.Message.Key value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                key_ = value.getNumber();
                onChanged();
                return this;
            }
            /**
             * <code>required .Message.Key key = 2;</code>
             * @return This builder for chaining.
             */
            public Builder clearKey() {
                bitField0_ = (bitField0_ & ~0x00000002);
                key_ = 0;
                onChanged();
                return this;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:Message)
        }

        // @@protoc_insertion_point(class_scope:Message)
        private static final fr.maelgui.wordclockmanager.MessagesProto.Message DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new fr.maelgui.wordclockmanager.MessagesProto.Message();
        }

        public static fr.maelgui.wordclockmanager.MessagesProto.Message getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @java.lang.Deprecated public static final com.google.protobuf.Parser<Message>
                PARSER = new com.google.protobuf.AbstractParser<Message>() {
            @java.lang.Override
            public Message parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Message(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Message> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Message> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public fr.maelgui.wordclockmanager.MessagesProto.Message getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Message_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Message_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\016messages.proto\"\313\001\n\007Message\022\r\n\005value\030\001 " +
                        "\001(\004\022\031\n\003key\030\002 \002(\0162\014.Message.Key\"\225\001\n\003Key\022\010" +
                        "\n\004TIME\020\000\022\017\n\013TEMPERATURE\020\001\022\020\n\014TEMPERATURE" +
                        "S\020\002\022\t\n\005TIMER\020\003\022\010\n\004MODE\020\004\022\014\n\010FUNCTION\020\005\022\016" +
                        "\n\nBRIGHTNESS\020\006\022\r\n\tTHRESHOLD\020\007\022\014\n\010ROTATIO" +
                        "N\020\010\022\006\n\002OK\020\t\022\t\n\005ERROR\020\nB,\n\033fr.maelgui.wor" +
                        "dclockmanagerB\rMessagesProto"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        });
        internal_static_Message_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_Message_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Message_descriptor,
                new java.lang.String[] { "Value", "Key", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
